//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LogMessage.proto
namespace LoggingServices
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogMessage")]
  public partial class LogMessage : global::ProtoBuf.IExtensible
  {
    public LogMessage() {}
    
    private string _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private LoggingServices.Level _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public LoggingServices.Level Level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Level")]
    public enum Level
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INFO", Value=0)]
      INFO = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WARNING", Value=1)]
      WARNING = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR", Value=2)]
      ERROR = 2
    }
  
}